### ISSUE TITLE
How to hide this piece

### ISSUE THREAD

**Issue by xuexiaoao** [abraztsov/react-sweet-progress#2]
![image](https://user-images.githubusercontent.com/18185523/41826142-d4131e66-7859-11e8-8c07-56b1a987fc90.png)

**Comment by nickbullll** [comment]
This lib hasn't got this functionality

**Comment by xuexiaoao** [comment]
thanks

**Comment by nickbullll** [comment]
Now you can do it with `trailColor` (can be read in README)

```
<Progress
  theme={
    {
      default: {
        trailColor: 'transparent', // or any custom color
      },
  }
/>
```

**Comment by xuexiaoao** [comment]
thank you
