### ISSUE TITLE
"src" or "lib" directory missing if installing 1.1.1 from npm 

### ISSUE THREAD

**Issue by luxwan13** [abraztsov/react-sweet-progress#4]
After installing the latest version with npm and run webpack, I got the error:
These dependencies were not found:
* react-sweet-progress in ./assets/js/app.js
* react-sweet-progress/lib/style.css in ./assets/js/app.js
I thought I had something wrong in webpack or somewhere else. It took me an hour or so to realise that your package does not contain any actual source files apart from some config stuff. 
I used your library in another project before and I didn't encounter this issue. Then I figured out that my another project was using a previous version which is 1.1.0. 
You must have forgotten to upload the src or lib directory to npm with your 1.1.1 update.

**Comment by nickbullll** [comment]
Thank you! Fixed in 1.1.2
